### PR TITLE
[Issue 30] Unique Input ID

### PR DESCRIPTION
**Pull request by pavlo-vavruk**
Fix uniqueness of input Ids. Now we can use more than one component on a single page.

### CODE REVIEW

**Comment by channox32** [comment]
Thanks ;)

**Comment by achepey** [comment]
This fix doesn't seem to be in NPM yet. Any ideas when that will be?

**Comment by zakangelle** [comment]
Hey, I apologize for the delay on this. I will get this merged in tonight!

**Comment by achepey** [comment]
Sorry to be a bother, but I am still not seeing 3.3.1 on NPM. Any ideas on when that would be?

**Comment by channox32** [comment]
@achepey While waiting for the fix, you may want to have a work-around in it. In my case I just copied the Base code and created a new component for the mean time while the fix is not yet reflective in the current version in NPM.

**Comment by achepey** [comment]
Any change this will get merged soon?
Would rather not have to copy the base code and create my own component.

**Comment by zakangelle** [comment]
I very much apologize for taking so long to review and merge this. Thanks for helping out!

**Pull request merged**
