### PR TITLE
Added OnKeyDown Event as well as a class for the Icon

### LINKED ISSUE #16: Add a custom Class for the Show/Hide Button
It's pretty hard to style it since it doesn't get *any* class on top of it, of course there is the inline styling, but this for example messes up with my external css styling.

### PR DESCRIPTION
**Pull request by lucidlemon**
The onKeyDown is very useful for checking if the Enter key has been pressed (among other things), otherwise it's pretty hard to check if the user tried to submit the form using enter (afaik the onChange does not submit a keyCode).

Also adds a Class for the Icon, which makes external styling a lot easier. I don't think this should need too much explanation, it's lightweight and can make everything easier.

fixes #16

### CODE REVIEW

**Comment by zakangelle** [comment]
I might be misunderstanding, but as long as your form fields and submit button are within the same `<form>` element, hitting Enter will always submit the form. You shouldn't need to handle it in JS.

```js
render() {
  return (
    <form onSubmit={this.handleSubmit.bind(this)}>
      <PasswordMask {...yourProps} />

      <input type="submit" value="Submit" />
    </form>
  );
}
```

Let me know if I'm missing something though.

I agree on adding a class for styling the button -- for clarity, I think we should call it `buttonClassName`, and possibly rename the `className` option currently used for styling the input field to `inputClassName`.

Also, I'm kicking around the idea of moving the default styles to an optional stylesheet that ships with the lib vs. being injected inline to the component. This would add a little extra implementation overhead for the developer (if they want default styles), but would make styling 100% versatile whether you use CSS or JS to do your styles.

Thoughts?

**Comment by lucidlemon** [comment]
Yeah I fully agree with both of your suggestions. Makes sense to me and shouldn't hurt too much.

And yes, you could handle the submit like that, true. I did it without a form tag within my login so I forgot to handle it like that, but I guess I could do that. My bad.

**Comment by lucidlemon** [comment]
For some reason the "onSubmit" does not fire in my form when pressing enter inside the password-mask?

**Comment by BTMPL** [comment]
It looks like the field is intercepting the submit event somehow, or it triggers some browser security feature when used in a form without a submit button, e.g.:

https://codesandbox.io/s/x7kp486lrw

**Comment by lucidlemon** [comment]
Still doesn't work with the workaround provided by @BTMPL in Safari.
Could you please merge that?

**Comment by zakangelle** [comment]
@lucidlemon Please update `iconClassName` to `buttonClassName` and I'll get this merged in. Thanks.

**Comment by zakangelle** [comment]
@lucidlemon Also README docs should be updated to reflect these changes and tests need to be updated as well.

**Comment by lucidlemon** [comment]
@zakangelle done.
I also did one more thing: `props.useVendorStyles` is a bool which defaults to `true`, if it is it renders your css. If it is set to false it only applies styles by the user.

**Comment by zakangelle** [comment]
Looks really good! Merging. I like the `useVendorStyles` too. Still on the fence on whether or not I want to ship an optional stylesheet.

**Comment by zakangelle** [comment]
`v3.0.0` stamped and published. Appreciate your contributions man.

**Pull request merged**
